apiVersion: v1
kind: Service
metadata:
  name: opengist-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      name: http
    - port: {{ .Values.service.ports.ssh }}
      targetPort: {{ .Values.service.ports.ssh }}
      name: ssh
  selector:
    app: opengist
