name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.0
      
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.1
      with:
        config: '${{ github.workspace }}/cr.yaml'
