name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: v3.8.0
      
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        config: '${{ github.workspace }}/cr.yaml'
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"
